import pandas as pd

# Real internship listings
real_entries = [
    "Software Engineer Intern at XYZ Corp, apply at xyz.com",
    "Internship at ABC Inc, requires 2 years experience",
    "Data Science Intern position at DataCorp, apply via LinkedIn",
    "Marketing Internship at BrightFuture, stipend provided",
    "Machine Learning Intern at TechLabs, Python skills required",
    "UX Design Internship at Creative Minds, remote option available",
    "Business Analyst Intern at FinGrowth, MS Excel experience preferred",
    "Backend Developer Intern at CodeNest, apply with GitHub profile",
    "Social Media Marketing Intern at BuzzReach, must know Canva",
    "Cybersecurity Internship at SecureSoft, knowledge of Linux required",
    "Product Management Intern at InnovateX, MBA preferred",
    "Content Writing Intern at WordFluent, apply with writing samples",
    "Graphic Design Intern at ArtistryHub, must know Adobe Suite",
    "Research Assistant Intern at BioGen Labs, biology background needed",
    "Sales Intern at QuickSell Inc., excellent communication required",
    "Frontend Developer Intern at WebCraft, React.js experience needed",
    "Cloud Computing Intern at SkyNet Solutions, AWS knowledge preferred",
    "Digital Marketing Intern at GrowEasy, SEO skills required",
    "AI Research Intern at DeepMind Labs, TensorFlow experience a plus",
    "Finance Intern at WealthBridge, accounting knowledge required",
    "Mobile App Developer Intern at AppVibe, Flutter skills preferred",
    "HR Intern at PeopleFirst, organizational skills needed",
    "Network Engineer Intern at ConnectSphere, CCNA certification a plus",
    "Copywriting Intern at AdSpark, creative writing skills required",
    "Environmental Research Intern at GreenWave, sustainability knowledge needed",
    "Game Development Intern at PlayForge, Unity experience required",
    "Operations Intern at LogiChain, supply chain knowledge preferred",
    "Video Editing Intern at MediaGlow, Adobe Premiere skills needed",
    "Blockchain Intern at CryptoCore, Solidity knowledge a plus",
    "Customer Support Intern at HelpDesk Pro, communication skills required",
    "Web Developer Intern at SiteBuilder, WordPress experience preferred",
    "Public Relations Intern at BrandVoice, media relations skills needed",
    "DevOps Intern at CloudPeak, Docker and Kubernetes knowledge required",
    "Market Research Intern at InsightTrend, data analysis skills preferred",
    "Animation Intern at FrameFlow, After Effects proficiency needed",
    "Quality Assurance Intern at TestRight, manual testing experience a plus",
    "Database Admin Intern at DataVault, SQL skills required",
    "E-commerce Intern at ShopTrend, Shopify experience preferred",
    "Event Management Intern at FestiveVibes, planning skills needed",
    "Robotics Intern at AutoTech, ROS knowledge preferred",
    "Legal Intern at LawFirm Inc., research skills required",
    "Content Marketing Intern at StoryBrand, blogging experience needed",
    "AR/VR Intern at VisionTech, Unreal Engine skills preferred",
    "Supply Chain Intern at TradeFlow, logistics knowledge required",
    "Illustration Intern at ArtVibe, digital art skills needed",
    "Technical Writing Intern at TechDocs, documentation skills required",
    "Embedded Systems Intern at IoT Innovations, C programming needed",
    "Growth Hacking Intern at ScaleUp, analytics skills preferred",
    "IT Support Intern at TechAid, troubleshooting skills required",
    "Policy Research Intern at ThinkTank, political science background needed",
    "AI Ethics Intern at FutureProof AI, Knowledge of AI principles and strong analytical skills required",
"Full Stack Developer Intern at Nexlify, Experience with JavaScript frameworks preferred",
"Sustainability Analyst Intern at EcoTrend Solutions, Background in environmental science or data analysis required",
"Cloud Security Intern at CyberCloud Inc., Knowledge of cloud platforms (AWS, Azure, or GCP) required",
"Healthcare Data Intern at MediStats, Proficiency in Python or R and familiarity with healthcare datasets preferred",
"Augmented Reality Content Intern at ARTrendz, Experience with ARKit or ARCore a plus",
"FinTech Developer Intern at PayWave, Knowledge of APIs and secure coding practices required",
"Urban Planning Intern at CityScope Designs, Background in urban studies or geography preferred",
"IoT Developer Intern at SmartConnect Labs, Knowledge of MQTT or IoT protocols required",
"Corporate Social Responsibility Intern at ImpactFirst, Strong communication and project management skills needed",
"3D Modeling Intern at DesignForge, Proficiency in Blender or Maya required",
"Data Engineering Intern at Streamline Analytics, Experience with ETL processes preferred",
"EdTech Content Intern at LearnSphere, Background in education or instructional design a plus",
"Network Security Intern at SafeNet Systems, Familiarity with firewalls and penetration testing tools preferred",
"Product Design Intern at InnovateWorks, Experience with Figma or Sketch required",
"Bioinformatics Intern at GeneQuest Labs, Knowledge of bioinformatics tools like BLAST or R required",
"Customer Success Intern at UserBloom, Strong interpersonal skills required",
"Game Design Intern at PixelCraft Studios, Experience with Godot or Unreal Engine preferred",
"Renewable Energy Intern at SolarPeak, Background in engineering or environmental science needed",
"Journalism Intern at NewsPulse Media, Strong writing skills and AP style knowledge required",
"Database Admin Intern at DataVault, SQL skills required",
"E-commerce Intern at ShopTrend, Shopify experience preferred",

]

# Fake/scam internship listings
fake_entries = [
    "Work from home internship, earn $5000/month, no experience needed",
    "Immediate joining, send $100 for registration",
    "Online internship, make money fast! No skills required",
    "Pay Rs.200 and get guaranteed placement",
    "Urgent hiring! Pay to register now!",
    "Earn $100/day doing simple tasks from home",
    "Deposit $50 to get your offer letter",
    "Join now! No interview, pay upfront for instant joining",
    "Only today! Pay registration fee and get placed",
    "Register with $25 and receive your job letter by email",
    "Click here to start earning from day one with our internship",
    "Guaranteed job after internship, only $150 to enroll",
    "Send money via PayPal to confirm your internship spot",
    "No interview needed! Just send your payment and start",
    "Pay to get placed at top companies instantly",
    "Earn $2000/week with our exclusive internship, pay $75 to join",
    "Limited seats! Pay Rs.500 for internship confirmation",
    "Work from anywhere, no skills needed, send $30 now",
    "Get hired today! Pay registration fee of $99",
    "Fast cash internship, pay upfront for training materials",
    "Join our team, send Rs.1000 for processing fee",
    "No experience? No problem! Pay $50 to start earning",
    "Exclusive internship offer, pay $200 for placement",
    "Instant job offer after paying $25 registration fee",
    "Work online, earn big, pay Rs.300 to secure your spot",
    "High-paying internship, send $40 for offer letter",
    "Join top MNCs, pay Rs.1500 for guaranteed placement",
    "Earn while learning, pay $60 for internship kit",
    "Quick internship placement, send $80 via UPI",
    "No resume needed! Pay $100 and start working",
    "Premium internship program, pay Rs.400 to enroll",
    "Get placed in 24 hours, pay $50 registration fee",
    "Online job internship, send $20 to confirm",
    "Pay Rs.250 for instant internship offer letter",
    "Work from home, pay $150 for training and start earning",
    "Limited time offer! Pay $30 for internship slot",
    "Earn $5000/month, send Rs.600 for registration",
    "No skills required, pay $45 to join our internship",
    "Get your dream job, pay $200 for placement fee",
    "Instant internship, pay Rs.100 for confirmation",
    "Work online, earn fast, send $25 for offer",
    "Pay $75 for guaranteed internship at top firms",
    "Join today, pay Rs.200 for instant access",
    "High salary internship, pay $50 for registration",
    "No interview, pay Rs.300 and start immediately",
    "Exclusive work-from-home internship, send $100 now",
    "Pay $40 for internship confirmation email",
    "Earn big with our internship, pay Rs.500 upfront",
    "Fast-track internship, pay $60 to secure your place",
    "Join our elite internship, send $150 for enrollment",
]

# Create and save the dataset
data = {
    'text': real_entries + fake_entries,
    'label': [1] * len(real_entries) + [0] * len(fake_entries)
}

# Debug: Print lengths to diagnose the issue
print(f"Length of real_entries: {len(real_entries)}")
print(f"Length of fake_entries: {len(fake_entries)}")
print(f"Length of text: {len(data['text'])}")
print(f"Length of label: {len(data['label'])}")

df = pd.DataFrame(data)
df.to_csv('data.csv', index=False, quoting=1)
print("✅ data.csv has been created with 100 entries (50 real, 50 fake).")